version: 2
jobs:
  build:
    working_directory: ~/working_dir
    machine: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "c1:2e:8f:1e:f2:e2:a8:74:a2:f5:a6:77:e8:60:92:49"
      - run:
          name: scp dockerfile dir
          command: scp -r -P 37292 ./dockerfile root@vlsys.net:/tmp/
      - run:
          name: build image
          command: ssh -p 37292 root@vlsys.net "source /etc/profile; docker build -t ddns-updater:arm64 /tmp/dockerfile"
      - run:
          name: archive image
          command: ssh -p 37292 root@vlsys.net "source /etc/profile; docker save ddns-updater:arm64 > /tmp/ddns-updater.arm64.tar"
      - run:
          name: get image
          command: scp -P 37292 root@vlsys.net:/tmp/ddns-updater.arm64.tar ~/working_dir/ddns-updater.arm64.tar
      - run:
          name: clean up
          command: ssh -p 37292 root@vlsys.net "source /etc/profile; rm -rf /tmp/dockerfile; rm -rf /tmp/ddns-updater.arm64.tar"
      - save_cache:
          key: image-{{ epoch }}
          paths:
            - ~/working_dir/ddns-updater.arm64.tar

  deploy:
    working_directory: ~/working_dir
    machine: true
    steps:
      - restore_cache:
          keys:
            - image
      - run:
          name: restore image
          command: docker load < ~/working_dir/ddns-updater.arm64.tar
      - run:
          name: login arc repo
          command: docker login $ACR_LOGIN_SERVER --username $ACR_LOGIN_ID --password $ACR_LOGIN_PASS
      - run:
          name: set version
          command: |
            echo 'export VERSION=v1.1' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: set tag as current version 
          command: docker tag ddns-updater:arm64 $ACR_LOGIN_SERVER/ddns-updater:$VERSION
      - run:
          name: push image as current version
          command: docker push $ACR_LOGIN_SERVER/ddns-updater:$VERSION
      - run:
          name: set tag as latest version
          command: docker tag ddns-updater:arm64 $ACR_LOGIN_SERVER/ddns-updater:latest
      - run:
          name: push image as latest version
          command: docker push $ACR_LOGIN_SERVER/ddns-updater:latest

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - /feature.*/
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master