version: 2
jobs:
  build:
    working_directory: ~/working_dir
    machine: true
    steps:
      - checkout
      - run:
          name: build image 
          command: docker build -t ddns-updater:tmp ./dockerfile
      - run:
          name: save image
          command: |
            mkdir cache_dir
            docker save ddns-updater:tmp > ./cache_dir/ddns-updater.tar
      - save_cache:
          key: image-{{ epoch }}
          paths:
            - ~/working_dir/cache_dir
  ssh_test:
    working_directory: ~/working_dir
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "c1:2e:8f:1e:f2:e2:a8:74:a2:f5:a6:77:e8:60:92:49"
      - run:
          name: ssh test
          command: ssh -p 27292 yusaito@vlsys.net "echo 'Hello, collard! >> /tmp/test'"

  deploy:
    working_directory: ~/working_dir
    machine: true
    steps:
      - restore_cache:
          keys:
            - image
      - run:
          name: restore image
          command: docker load < ./cache_dir/ddns-updater.tar
      - run:
          name: login arc repo
          command: docker login $ACR_LOGIN_SERVER --username $ACR_LOGIN_ID --password $ACR_LOGIN_PASS
      - run:
          name: get date for image tag
          command: |
            echo 'export VERSION=`date +"%Y%m%d%H%M%S"`' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: set tag as current version 
          command: docker tag ddns-updater:tmp $ACR_LOGIN_SERVER/ddns-updater:$VERSION
      - run:
          name: push image as current version
          command: docker push $ACR_LOGIN_SERVER/ddns-updater:$VERSION
      - run:
          name: set tag as latest version
          command: docker tag ddns-updater:tmp $ACR_LOGIN_SERVER/ddns-updater:latest
      - run:
          name: push image as latest version
          command: docker push $ACR_LOGIN_SERVER/ddns-updater:latest

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master